version: '3.8'
services:
  payment-service-app:
    image: payment-service-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - keycloak
    environment:
      # Валидация JWT по JWKS (без проверки issuer — удобно для dev)
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/demo/protocol/openid-connect/certs

  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin        # имя пользователя
      POSTGRES_PASSWORD: secret   # пароль
      POSTGRES_DB: payment-db     # имя БД по умолчанию
      LC_MESSAGES: en_US.UTF-8    # язык ошибок - английский
    ports:
      - "5432:5432"               # проброс порта PostgreSQL
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com # учётка для входа
      PGADMIN_DEFAULT_PASSWORD: admin        # пароль для входа
    ports:
      - "8081:80"                 # UI будет доступен по localhost:8081
    depends_on:
      - postgres
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    command: start-dev --http-port=8080 --hostname-strict=false --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8085:8080"               # UI Keycloak по http://localhost:8085
    restart: unless-stopped
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json

volumes:
  pgdata:
